name: Publicar Imagen Docker

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  build-and-push-to-ghcr:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

    permissions:
      contents: read
      packages: write # Permiso para publicar en GHCR

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Token automático de GitHub

      - name: Construir y publicar la imagen (CD)
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ghcr.io/ingsis-second-chance/permissions-manager:${{ env.IMAGE_TAG }}
          file: ./Dockerfile

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ghcr

    env:
      SSH_KEY: ${{ github.ref_name == 'main' && secrets.SSH_KEY_PROD || secrets.SSH_KEY_DEV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0 # Evita exponer la clave privada en los logs
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Deploy to Azure VM (prod)
        if: github.ref_name == 'main'
        run: |
          ssh -v -o StrictHostKeyChecking=no ingsis@${{ secrets.VM_PROD_IP }} << ENDSSH
          cd infra
          docker compose -f docker-compose.prod.yml down permissions-manager
          docker compose -f docker-compose.prod.yml pull permissions-manager
          docker compose -f docker-compose.prod.yml up -d permissions-manager
          ENDSSH

      - name: Deploy to Azure VM (dev)
        if: github.ref_name != 'main'
        run: |
          ssh -v -o StrictHostKeyChecking=no ingsis@${{ secrets.VM_DEV_IP }} << ENDSSH
          cd infra
          docker compose -f docker-compose.dev.yml down permissions-manager
          docker compose -f docker-compose.dev.yml pull permissions-manager
          docker compose -f docker-compose.dev.yml up -d permissions-manager
          ENDSSH